domi
Domino-Blockchain/wallet-adapter pull request #1
Opened 2023-04-03 14:22 UTC by rs-Nenad

2023-04-03 15:08 UTC, sviatoslav-alekseev approved these changes

2023-04-04 13:52 UTC, dragvs approved these changes

2023-04-04 13:52 UTC, dragvs commented on src/adapter.ts
>          'data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjUzMCIgd2lkdGg9IjUzMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJtLTEtMWg1MzJ2NTMyaC01MzJ6IiBmaWxsPSJub25lIi8+PGcgZmlsbD0iIzAwZmZh
What's in this icon? Should we replace it? And the one below

2023-04-11 13:47 UTC, dragvs requested changes

2023-04-11 13:47 UTC, dragvs commented on yarn-error.log
> +Arguments:
I'm not sure we need this file

2023-04-12 14:20 UTC, rs-Nenad commented on yarn-error.log
> +Arguments:
deleted, and added to .gitignore

2023-04-12 14:41 UTC, dragvs approved these changes

2023-04-12 14:43 UTC, merged